/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/assets": {
    /**
     * List static assets
     * @description Get a list of available static assets
     */
    get: {
      parameters: {
        query?: {
          /** @description Asset type filter */
          type?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "*/*": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "*/*": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/assets/{path}": {
    /**
     * Serve static assets
     * @description Serve static files like CSS, JS, images with appropriate headers
     */
    get: {
      parameters: {
        path: {
          /** @description Asset path */
          path: string;
        };
      };
      responses: {
        /** @description Asset content */
        200: {
          content: never;
        };
        /** @description Not Found */
        404: {
          content: {
            "*/*": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/change-password": {
    /**
     * Change password
     * @description Change user password
     */
    post: {
      /** @description Password change data */
      requestBody: {
        content: {
          "application/json": {
            current_password?: string;
            new_password?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/login": {
    /**
     * Login user
     * @description Authenticate user with username/email and password
     */
    post: {
      /** @description Login credentials */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.LoginRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.LoginResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/logout": {
    /**
     * Logout user
     * @description Blacklist the current JWT token
     */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/me": {
    /**
     * Get current user
     * @description Get current authenticated user information
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserResponse"];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/register": {
    /**
     * Register new user
     * @description Create a new user account
     */
    post: {
      /** @description User registration data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.UserCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Conflict */
        409: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contact/form": {
    /**
     * Submit contact form
     * @description Submit a contact form and optionally subscribe to newsletter
     */
    post: {
      /** @description Contact form data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_ae-saas-basic_ae-saas-basic_internal_models.ContactFormRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-saas-basic_ae-saas-basic_internal_models.ContactFormResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contact/newsletter": {
    /**
     * Get newsletter subscriptions
     * @description Get all newsletter subscriptions for admin users
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-saas-basic_ae-saas-basic_internal_models.Newsletter"][];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contact/newsletter/unsubscribe": {
    /**
     * Unsubscribe from newsletter
     * @description Unsubscribe an email from the newsletter
     */
    delete: {
      parameters: {
        query: {
          /** @description Email to unsubscribe */
          email: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contacts": {
    /**
     * Get all contacts
     * @description Get a paginated list of all contacts
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Filter by active status */
          active?: boolean;
          /** @description Filter by contact type */
          type?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ListResponse"];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create a new contact
     * @description Create a new contact
     */
    post: {
      /** @description Contact creation data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.ContactCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ContactResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contacts/{id}": {
    /**
     * Get contact by ID
     * @description Get a specific contact by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Contact ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ContactResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update a contact
     * @description Update an existing contact by ID
     */
    put: {
      parameters: {
        path: {
          /** @description Contact ID */
          id: number;
        };
      };
      /** @description Contact update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.ContactUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ContactResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete a contact
     * @description Soft delete a contact by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Contact ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/customers": {
    /**
     * Get all customers
     * @description Get a paginated list of customers for the authenticated tenant
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Filter by active status */
          active?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ListResponse"];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create a new customer
     * @description Create a new customer within the authenticated tenant
     */
    post: {
      /** @description Customer creation data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.CustomerCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.CustomerResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/customers/{id}": {
    /**
     * Get customer by ID
     * @description Get a specific customer by its ID within the authenticated tenant
     */
    get: {
      parameters: {
        path: {
          /** @description Customer ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.CustomerResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update a customer
     * @description Update an existing customer by ID within the authenticated tenant
     */
    put: {
      parameters: {
        path: {
          /** @description Customer ID */
          id: number;
        };
      };
      /** @description Customer update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.CustomerUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.CustomerResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete a customer
     * @description Soft delete a customer by ID within the authenticated tenant
     */
    delete: {
      parameters: {
        path: {
          /** @description Customer ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails": {
    /**
     * Get all emails
     * @description Get a paginated list of all emails
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Filter by email status */
          status?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ListResponse"];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails/send": {
    /**
     * Send an email
     * @description Create and queue an email for sending
     */
    post: {
      /** @description Email send data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.EmailSendRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.EmailResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails/stats": {
    /**
     * Get email statistics
     * @description Get email statistics including counts by status
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: Record<string, never>;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails/{id}": {
    /**
     * Get email by ID
     * @description Get a specific email by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Email ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.EmailResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/health": {
    /**
     * Health check
     * @description Check the health status of the API and database
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.HealthResponse"];
          };
        };
        /** @description Service Unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/logo": {
    /**
     * Get company logo
     * @description Serve the company logo in various formats
     */
    get: {
      parameters: {
        query?: {
          /** @description Logo format (svg|png|jpg) */
          format?: string;
        };
      };
      responses: {
        /** @description Logo file */
        200: {
          content: never;
        };
        /** @description Not Found */
        404: {
          content: {
            "*/*": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/ping": {
    /**
     * Ping check
     * @description Simple ping endpoint
     */
    get: {
      responses: {
        /** @description pong */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/plans": {
    /**
     * Get all plans
     * @description Get a paginated list of all plans
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Filter by active status */
          active?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ListResponse"];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create a new plan
     * @description Create a new subscription plan
     */
    post: {
      /** @description Plan creation data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.PlanCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.PlanResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Conflict */
        409: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/plans/{id}": {
    /**
     * Get plan by ID
     * @description Get a specific plan by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Plan ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.PlanResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update a plan
     * @description Update an existing plan by ID
     */
    put: {
      parameters: {
        path: {
          /** @description Plan ID */
          id: number;
        };
      };
      /** @description Plan update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.PlanUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.PlanResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete a plan
     * @description Soft delete a plan by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Plan ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/templates/{type}/{template}": {
    /**
     * Preview templates
     * @description Serve template files for preview purposes
     */
    get: {
      parameters: {
        path: {
          /** @description Template type (email|pdf) */
          type: string;
          /** @description Template name */
          template: string;
        };
      };
      responses: {
        /** @description Template content */
        200: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: {
            "*/*": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "*/*": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/user-settings": {
    /**
     * Get user settings
     * @description Get the authenticated user's settings
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserSettingsResponse"];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update user settings
     * @description Update the authenticated user's settings
     */
    put: {
      /** @description User settings update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.UserSettingsUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserSettingsResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/user-settings/reset": {
    /**
     * Reset user settings
     * @description Reset the authenticated user's settings to default values
     */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserSettingsResponse"];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Contact form submission request */
    "github_com_ae-saas-basic_ae-saas-basic_internal_models.ContactFormRequest": {
      /** @example john.doe@example.com */
      email: string;
      /** @example I am interested in learning more about your therapy services. */
      message: string;
      /** @example John Doe */
      name: string;
      /** @example true */
      newsletter?: boolean;
      /** @example website */
      source: string;
      /** @example Inquiry about therapy services */
      subject: string;
      /** @example 2025-08-03T10:00:00Z */
      timestamp?: string;
    };
    /** @description Contact form submission response */
    "github_com_ae-saas-basic_ae-saas-basic_internal_models.ContactFormResponse": {
      /** @example Contact form submitted successfully */
      message?: string;
      /** @example true */
      newsletterAdded?: boolean;
      /** @example Successfully subscribed to newsletter */
      newsletterMessage?: string;
    };
    "github_com_ae-saas-basic_ae-saas-basic_internal_models.Newsletter": {
      /** @example 2025-08-03T10:00:00Z */
      createdAt?: string;
      /** @example john.doe@example.com */
      email?: string;
      /** @example 1 */
      id?: number;
      /** @example mental_health */
      interest?: string;
      /** @example 2025-08-03T10:00:00Z */
      lastContact?: string;
      /** @example John Doe */
      name?: string;
      /** @example website */
      source?: string;
      /** @example 2025-08-03T10:00:00Z */
      updatedAt?: string;
    };
    "models.APIResponse": {
      data?: unknown;
      error?: string;
      message?: string;
      success?: boolean;
    };
    "models.ContactCreateRequest": {
      city?: string;
      country?: string;
      email?: string;
      first_name: string;
      last_name: string;
      mobile?: string;
      notes?: string;
      phone?: string;
      street?: string;
      type?: string;
      zip?: string;
    };
    "models.ContactResponse": {
      active?: boolean;
      city?: string;
      country?: string;
      created_at?: string;
      email?: string;
      first_name?: string;
      id?: number;
      last_name?: string;
      mobile?: string;
      notes?: string;
      phone?: string;
      street?: string;
      type?: string;
      zip?: string;
    };
    "models.ContactUpdateRequest": {
      active?: boolean;
      city?: string;
      country?: string;
      email?: string;
      first_name?: string;
      last_name?: string;
      mobile?: string;
      notes?: string;
      phone?: string;
      street?: string;
      type?: string;
      zip?: string;
    };
    "models.CustomerCreateRequest": {
      city?: string;
      country?: string;
      email: string;
      name: string;
      payment_method?: string;
      phone?: string;
      plan_id: number;
      street?: string;
      tax_id?: string;
      tenant_id: number;
      vat?: string;
      zip?: string;
    };
    "models.CustomerResponse": {
      active?: boolean;
      city?: string;
      country?: string;
      created_at?: string;
      email?: string;
      id?: number;
      name?: string;
      payment_method?: string;
      phone?: string;
      plan?: components["schemas"]["models.PlanResponse"];
      plan_id?: number;
      status?: string;
      street?: string;
      tax_id?: string;
      tenant?: components["schemas"]["models.TenantResponse"];
      tenant_id?: number;
      vat?: string;
      zip?: string;
    };
    "models.CustomerUpdateRequest": {
      active?: boolean;
      city?: string;
      country?: string;
      email?: string;
      name?: string;
      payment_method?: string;
      phone?: string;
      plan_id?: number;
      status?: string;
      street?: string;
      tax_id?: string;
      vat?: string;
      zip?: string;
    };
    "models.EmailResponse": {
      created_at?: string;
      delivered_at?: string;
      error_message?: string;
      from?: string;
      id?: number;
      sent_at?: string;
      status?: string;
      subject?: string;
      to?: string;
    };
    "models.EmailSendRequest": {
      body: string;
      from: string;
      html_body?: string;
      subject: string;
      to: string;
    };
    "models.ErrorResponse": {
      code?: number;
      details?: string;
      error?: string;
    };
    "models.HealthResponse": {
      database?: string;
      status?: string;
      timestamp?: string;
      version?: string;
    };
    "models.ListResponse": {
      data?: unknown;
      pagination?: components["schemas"]["models.PaginationResponse"];
    };
    "models.LoginRequest": {
      password: string;
      username: string;
    };
    "models.LoginResponse": {
      token?: string;
      user?: components["schemas"]["models.UserResponse"];
    };
    "models.PaginationResponse": {
      limit?: number;
      page?: number;
      total?: number;
      total_pages?: number;
    };
    "models.PlanCreateRequest": {
      active?: boolean;
      currency?: string;
      description?: string;
      features?: string;
      invoice_period?: string;
      max_clients?: number;
      max_users?: number;
      name: string;
      price: number;
      slug: string;
    };
    "models.PlanResponse": {
      active?: boolean;
      created_at?: string;
      currency?: string;
      description?: string;
      features?: string;
      id?: number;
      invoice_period?: string;
      max_clients?: number;
      max_users?: number;
      name?: string;
      price?: number;
      slug?: string;
    };
    "models.PlanUpdateRequest": {
      active?: boolean;
      currency?: string;
      description?: string;
      features?: string;
      invoice_period?: string;
      max_clients?: number;
      max_users?: number;
      name?: string;
      price?: number;
    };
    "models.TenantResponse": {
      created_at?: string;
      id?: number;
      name?: string;
      slug?: string;
    };
    "models.UserCreateRequest": {
      email: string;
      first_name: string;
      last_name: string;
      password: string;
      role?: string;
      tenant_id: number;
      username: string;
    };
    "models.UserResponse": {
      active?: boolean;
      created_at?: string;
      email?: string;
      first_name?: string;
      id?: number;
      last_name?: string;
      role?: string;
      tenant?: components["schemas"]["models.TenantResponse"];
      tenant_id?: number;
      username?: string;
    };
    "models.UserSettingsResponse": {
      id?: number;
      language?: string;
      settings?: string;
      theme?: string;
      timezone?: string;
      updated_at?: string;
      user_id?: number;
    };
    "models.UserSettingsUpdateRequest": {
      language?: string;
      settings?: string;
      theme?: string;
      timezone?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
