/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/admin/modules": {
    /**
     * Get registered modules
     * @description Get information about all registered modules in the system
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-saas-basic_ae-saas-basic_internal_modules.ModuleInfo"][];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/admin/modules/{name}": {
    /**
     * Get module details
     * @description Get detailed information about a specific module by name
     */
    get: {
      parameters: {
        path: {
          /** @description Module name */
          name: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-saas-basic_ae-saas-basic_internal_modules.ModuleInfo"];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/modules/demo/demo": {
    /**
     * Get demo information
     * @description Get information about the demo module
     */
    get: {
      responses: {
        /** @description Demo information */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/api/v1/modules/demo/items": {
    /**
     * Get all demo items
     * @description Retrieve all demo items from the demo module
     */
    get: {
      responses: {
        /** @description List of demo items */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    /**
     * Create a new demo item
     * @description Create a new demo item in the demo module
     */
    post: {
      /** @description Demo item data */
      requestBody: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Created demo item */
        201: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/modules/demo/items/{id}": {
    /**
     * Get demo item by ID
     * @description Retrieve a specific demo item by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Demo Item ID */
          id: number;
        };
      };
      responses: {
        /** @description Demo item details */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Demo item not found */
        404: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    /**
     * Update a demo item
     * @description Update an existing demo item by ID
     */
    put: {
      parameters: {
        path: {
          /** @description Demo Item ID */
          id: number;
        };
      };
      /** @description Updated demo item data */
      requestBody: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Updated demo item */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Demo item not found */
        404: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    /**
     * Delete a demo item
     * @description Delete a demo item by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Demo Item ID */
          id: number;
        };
      };
      responses: {
        /** @description Deletion confirmation */
        200: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Demo item not found */
        404: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/pdf/create": {
    /**
     * Generate PDF from template
     * @description Generate a PDF document based on a specified template and data
     */
    post: {
      /** @description PDF generation request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["handlers.PDFGenerateRequest"];
        };
      };
      responses: {
        /** @description PDF generated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["handlers.PDFGenerateResponse"];
          };
        };
        /** @description Invalid request */
        400: {
          content: {
            "application/json": components["schemas"]["handlers.ErrorResponse"];
          };
        };
        /** @description Failed to generate PDF */
        500: {
          content: {
            "application/json": components["schemas"]["handlers.ErrorResponse"];
          };
        };
      };
    };
  };
  "/api/v1/ping": {
    /**
     * Ping check
     * @description Simple ping endpoint
     */
    get: {
      responses: {
        /** @description pong */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/auth/change-password": {
    /**
     * Change password
     * @description Change user password
     */
    post: {
      /** @description Password change data */
      requestBody: {
        content: {
          "application/json": {
            current_password?: string;
            new_password?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/forgot-password": {
    /**
     * Request password reset
     * @description Send password reset link to user email
     */
    post: {
      /** @description User email */
      requestBody: {
        content: {
          "application/json": {
            email?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/generate-signup-token": {
    /**
     * Generate user signup token
     * @description Generate a token for inviting users to join a specific tenant
     */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: {
                expires_in?: string;
                token?: string;
              };
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Forbidden */
        403: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/login": {
    /**
     * Login user
     * @description Authenticate user with username/email and password
     */
    post: {
      /** @description Login credentials */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.LoginRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.LoginResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/logout": {
    /**
     * Logout user
     * @description Blacklist the current JWT token
     */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/me": {
    /**
     * Get current user
     * @description Get current authenticated user information
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserResponse"];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/new-password/{token}": {
    /**
     * Reset password
     * @description Reset user password with reset token
     */
    post: {
      parameters: {
        path: {
          /** @description Reset token */
          token: string;
        };
      };
      /** @description New password */
      requestBody: {
        content: {
          "application/json": {
            new_password?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/password-security": {
    /**
     * Get password security requirements
     * @description Returns the current password security requirements including minimum length and character requirements
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["utils.PasswordRequirements"];
          };
        };
      };
    };
  };
  "/auth/register": {
    /**
     * Register new user
     * @description Create a new user account. If a user-signup token is provided in Authorization header, user will join that tenant. Otherwise, company_name is required to create new tenant.
     */
    post: {
      parameters: {
        header?: {
          /** @description Bearer token for user signup invitation */
          Authorization?: string;
        };
      };
      /** @description User registration data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.UserCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Conflict */
        409: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/verify-email/{token}": {
    /**
     * Verify email address
     * @description Verify user email address with token from verification email
     */
    get: {
      parameters: {
        path: {
          /** @description Verification token */
          token: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/clients": {
    /**
     * Get all clients
     * @description Get a paginated list of all clients
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
        };
      };
      responses: {
        /** @description data: array of ClientResponse, total: int, page: int, limit: int */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description error: string */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Create a new client
     * @description Create a new client with first name, last name, and date of birth
     */
    post: {
      /** @description Client data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.CreateClientRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.ClientResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/clients/search": {
    /**
     * Search clients
     * @description Search clients by first name or last name
     */
    get: {
      parameters: {
        query: {
          /** @description Search query */
          q: string;
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/clients/{id}": {
    /**
     * Get a client by ID
     * @description Retrieve a specific client by their ID
     */
    get: {
      parameters: {
        path: {
          /** @description Client ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.ClientResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Update a client
     * @description Update an existing client's information
     */
    put: {
      parameters: {
        path: {
          /** @description Client ID */
          id: number;
        };
      };
      /** @description Client update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.UpdateClientRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.ClientResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Delete a client
     * @description Soft delete a client by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Client ID */
          id: number;
        };
      };
      responses: {
        /** @description No Content */
        204: {
          content: never;
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/contact/form": {
    /**
     * Submit contact form
     * @description Submit a contact form and optionally subscribe to newsletter
     */
    post: {
      /** @description Contact form data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_ae-saas-basic_ae-saas-basic_internal_models.ContactFormRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-saas-basic_ae-saas-basic_internal_models.ContactFormResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contact/newsletter": {
    /**
     * Get newsletter subscriptions
     * @description Get all newsletter subscriptions for admin users
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-saas-basic_ae-saas-basic_internal_models.Newsletter"][];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contact/newsletter/unsubscribe": {
    /**
     * Unsubscribe from newsletter
     * @description Unsubscribe an email from the newsletter
     */
    delete: {
      parameters: {
        query: {
          /** @description Email to unsubscribe */
          email: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contacts": {
    /**
     * Get all contacts
     * @description Get a paginated list of all contacts
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Filter by active status */
          active?: boolean;
          /** @description Filter by contact type */
          type?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ListResponse"];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create a new contact
     * @description Create a new contact
     */
    post: {
      /** @description Contact creation data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.ContactCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ContactResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contacts/{id}": {
    /**
     * Get contact by ID
     * @description Get a specific contact by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Contact ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ContactResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update a contact
     * @description Update an existing contact by ID
     */
    put: {
      parameters: {
        path: {
          /** @description Contact ID */
          id: number;
        };
      };
      /** @description Contact update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.ContactUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ContactResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete a contact
     * @description Soft delete a contact by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Contact ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/customers": {
    /**
     * Get all customers
     * @description Get a paginated list of customers for the authenticated tenant
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Filter by active status */
          active?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ListResponse"];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create a new customer
     * @description Create a new customer within the authenticated tenant
     */
    post: {
      /** @description Customer creation data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.CustomerCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.CustomerResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/customers/{id}": {
    /**
     * Get customer by ID
     * @description Get a specific customer by its ID within the authenticated tenant
     */
    get: {
      parameters: {
        path: {
          /** @description Customer ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.CustomerResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update a customer
     * @description Update an existing customer by ID within the authenticated tenant
     */
    put: {
      parameters: {
        path: {
          /** @description Customer ID */
          id: number;
        };
      };
      /** @description Customer update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.CustomerUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.CustomerResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete a customer
     * @description Soft delete a customer by ID within the authenticated tenant
     */
    delete: {
      parameters: {
        path: {
          /** @description Customer ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails": {
    /**
     * Get all emails
     * @description Get a paginated list of all emails
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Filter by email status */
          status?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ListResponse"];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails/send": {
    /**
     * Send an email
     * @description Create and queue an email for sending
     */
    post: {
      /** @description Email send data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.EmailSendRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.EmailResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails/stats": {
    /**
     * Get email statistics
     * @description Get email statistics including counts by status
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: Record<string, never>;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails/{id}": {
    /**
     * Get email by ID
     * @description Get a specific email by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Email ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.EmailResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/health": {
    /**
     * Health check
     * @description Check the health status of the API and database
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.HealthResponse"];
          };
        };
        /** @description Service Unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/plans": {
    /**
     * Get all plans
     * @description Get a paginated list of all plans
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Filter by active status */
          active?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.ListResponse"];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create a new plan
     * @description Create a new subscription plan
     */
    post: {
      /** @description Plan creation data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.PlanCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.PlanResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Conflict */
        409: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/plans/{id}": {
    /**
     * Get plan by ID
     * @description Get a specific plan by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Plan ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.PlanResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update a plan
     * @description Update an existing plan by ID
     */
    put: {
      parameters: {
        path: {
          /** @description Plan ID */
          id: number;
        };
      };
      /** @description Plan update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.PlanUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.PlanResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete a plan
     * @description Soft delete a plan by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Plan ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/static": {
    /**
     * List available static JSON files
     * @description Get a list of all JSON files available in the statics/json directory
     */
    get: {
      responses: {
        /** @description List of available JSON files */
        200: {
          content: {
            "*/*": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Failed to read directory */
        500: {
          content: {
            "*/*": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/static/{filename}": {
    /**
     * Serve static JSON files
     * @description Dynamically serve any JSON data file from the statics/json directory. Just drop a .json file in the directory and it becomes available at /static/{filename}
     */
    get: {
      parameters: {
        path: {
          /**
           * @description JSON filename (without .json extension)
           * @example "bundeslaender"
           */
          filename: string;
        };
      };
      responses: {
        /** @description JSON file content */
        200: {
          content: {
            "*/*": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Invalid file name */
        400: {
          content: {
            "*/*": {
              [key: string]: string;
            };
          };
        };
        /** @description File not found */
        404: {
          content: {
            "*/*": {
              [key: string]: string;
            };
          };
        };
        /** @description Failed to read file */
        500: {
          content: {
            "*/*": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/user-settings": {
    /**
     * Get user settings
     * @description Get the authenticated user's settings
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserSettingsResponse"];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update user settings
     * @description Update the authenticated user's settings
     */
    put: {
      /** @description User settings update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.UserSettingsUpdateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserSettingsResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/user-settings/reset": {
    /**
     * Reset user settings
     * @description Reset the authenticated user's settings to default values
     */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["models.APIResponse"] & {
              data?: components["schemas"]["models.UserSettingsResponse"];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["models.ErrorResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

// Export commonly used types
export type Client = components['schemas']['models.ClientResponse'];
export type CreateClientRequest = components['schemas']['models.CreateClientRequest'];

export interface components {
  schemas: {
    /** @description Contact form submission request */
    "github_com_ae-saas-basic_ae-saas-basic_internal_models.ContactFormRequest": {
      /** @example john.doe@example.com */
      email: string;
      /** @example I am interested in learning more about your therapy services. */
      message: string;
      /** @example John Doe */
      name: string;
      /** @example true */
      newsletter?: boolean;
      /** @example website */
      source: string;
      /** @example Inquiry about therapy services */
      subject: string;
      /** @example 2025-08-03T10:00:00Z */
      timestamp?: string;
    };
    /** @description Contact form submission response */
    "github_com_ae-saas-basic_ae-saas-basic_internal_models.ContactFormResponse": {
      /** @example Contact form submitted successfully */
      message?: string;
      /** @example true */
      newsletterAdded?: boolean;
      /** @example Successfully subscribed to newsletter */
      newsletterMessage?: string;
    };
    "github_com_ae-saas-basic_ae-saas-basic_internal_models.Newsletter": {
      /** @example 2025-08-03T10:00:00Z */
      createdAt?: string;
      /** @example john.doe@example.com */
      email?: string;
      /** @example 1 */
      id?: number;
      /** @example mental_health */
      interest?: string;
      /** @example 2025-08-03T10:00:00Z */
      lastContact?: string;
      /** @example John Doe */
      name?: string;
      /** @example website */
      source?: string;
      /** @example 2025-08-03T10:00:00Z */
      updatedAt?: string;
    };
    "github_com_ae-saas-basic_ae-saas-basic_internal_modules.ModuleInfo": {
      author?: string;
      description?: string;
      enabled?: boolean;
      name?: string;
      version?: string;
    };
    "handlers.ErrorResponse": {
      /** @example Additional error details */
      details?: string;
      /** @example Template name is required */
      error?: string;
    };
    "handlers.PDFGenerateRequest": {
      data: {
        [key: string]: unknown;
      };
      /** @example generated-report */
      fileName: string;
      /** @example report.html */
      templateName: string;
    };
    "handlers.PDFGenerateResponse": {
      /** @example generated-report.pdf */
      filename?: string;
      /** @example PDF generated successfully */
      message?: string;
      /** @example true */
      success?: boolean;
    };
    "models.APIResponse": {
      data?: unknown;
      error?: string;
      message?: string;
      success?: boolean;
    };
    "models.ClientResponse": {
      admission_date?: string;
      alternative_email?: string;
      alternative_first_name?: string;
      alternative_last_name?: string;
      alternative_phone?: string;
      city?: string;
      contact_email?: string;
      contact_first_name?: string;
      contact_last_name?: string;
      contact_phone?: string;
      created_at?: string;
      date_of_birth?: string;
      email?: string;
      first_name?: string;
      gender?: string;
      id?: number;
      invoiced_individually?: boolean;
      last_name?: string;
      notes?: string;
      phone?: string;
      primary_language?: string;
      provider_approval_code?: string;
      referral_source?: string;
      status?: string;
      street_address?: string;
      therapy_title?: string;
      unit_price?: number;
      updated_at?: string;
      zip?: string;
    };
    "models.ContactCreateRequest": {
      city?: string;
      country?: string;
      email?: string;
      first_name: string;
      last_name: string;
      mobile?: string;
      notes?: string;
      phone?: string;
      street?: string;
      type?: string;
      zip?: string;
    };
    "models.ContactResponse": {
      active?: boolean;
      city?: string;
      country?: string;
      created_at?: string;
      email?: string;
      first_name?: string;
      id?: number;
      last_name?: string;
      mobile?: string;
      notes?: string;
      phone?: string;
      street?: string;
      type?: string;
      zip?: string;
    };
    "models.ContactUpdateRequest": {
      active?: boolean;
      city?: string;
      country?: string;
      email?: string;
      first_name?: string;
      last_name?: string;
      mobile?: string;
      notes?: string;
      phone?: string;
      street?: string;
      type?: string;
      zip?: string;
    };
    "models.CreateClientRequest": {
      /** @example 2025-01-01 */
      admission_date?: string;
      /** @example johnny.d@example.com */
      alternative_email?: string;
      /** @example Johnny */
      alternative_first_name?: string;
      /** @example D */
      alternative_last_name?: string;
      /** @example +0987654321 */
      alternative_phone?: string;
      /** @example New York */
      city?: string;
      /** @example jane.smith@example.com */
      contact_email?: string;
      /** @example Jane */
      contact_first_name?: string;
      /** @example Smith */
      contact_last_name?: string;
      /** @example +1234567890 */
      contact_phone?: string;
      /** @example 1990-01-15 */
      date_of_birth?: string;
      /** @example john.doe@example.com */
      email?: string;
      /** @example John */
      first_name: string;
      /** @example male */
      gender?: string;
      /** @example false */
      invoiced_individually?: boolean;
      /** @example Doe */
      last_name: string;
      /** @example Additional notes about the client */
      notes?: string;
      /** @example +1234567890 */
      phone?: string;
      /** @example English */
      primary_language?: string;
      /** @example PROV123456 */
      provider_approval_code?: string;
      /** @example Doctor Smith */
      referral_source?: string;
      /** @example waiting */
      status?: string;
      /** @example 123 Main Street */
      street_address?: string;
      /** @example Cognitive Behavioral Therapy */
      therapy_title?: string;
      /** @example 150 */
      unit_price?: number;
      /** @example 12345 */
      zip?: string;
    };
    "models.CustomerCreateRequest": {
      city?: string;
      country?: string;
      email: string;
      name: string;
      payment_method?: string;
      phone?: string;
      plan_id: number;
      street?: string;
      tax_id?: string;
      tenant_id: number;
      vat?: string;
      zip?: string;
    };
    "models.CustomerResponse": {
      active?: boolean;
      city?: string;
      country?: string;
      created_at?: string;
      email?: string;
      id?: number;
      name?: string;
      payment_method?: string;
      phone?: string;
      plan?: components["schemas"]["models.PlanResponse"];
      plan_id?: number;
      status?: string;
      street?: string;
      tax_id?: string;
      tenant?: components["schemas"]["models.TenantResponse"];
      tenant_id?: number;
      vat?: string;
      zip?: string;
    };
    "models.CustomerUpdateRequest": {
      active?: boolean;
      city?: string;
      country?: string;
      email?: string;
      name?: string;
      payment_method?: string;
      phone?: string;
      plan_id?: number;
      status?: string;
      street?: string;
      tax_id?: string;
      vat?: string;
      zip?: string;
    };
    "models.EmailResponse": {
      created_at?: string;
      delivered_at?: string;
      error_message?: string;
      from?: string;
      id?: number;
      sent_at?: string;
      status?: string;
      subject?: string;
      to?: string;
    };
    "models.EmailSendRequest": {
      body: string;
      from: string;
      html_body?: string;
      subject: string;
      to: string;
    };
    "models.ErrorResponse": {
      code?: number;
      details?: string;
      error?: string;
    };
    "models.HealthResponse": {
      database?: string;
      settings?: components["schemas"]["models.HealthSettingsResponse"];
      status?: string;
      timestamp?: string;
      version?: string;
    };
    "models.HealthSettingsResponse": {
      mock_email?: boolean;
      rate_limit_enabled?: boolean;
    };
    "models.ListResponse": {
      data?: unknown;
      pagination?: components["schemas"]["models.PaginationResponse"];
    };
    "models.LoginRequest": {
      password: string;
      username: string;
    };
    "models.LoginResponse": {
      token?: string;
      user?: components["schemas"]["models.UserResponse"];
    };
    "models.PaginationResponse": {
      limit?: number;
      page?: number;
      total?: number;
      total_pages?: number;
    };
    "models.PlanCreateRequest": {
      active?: boolean;
      currency?: string;
      description?: string;
      features?: string;
      invoice_period?: string;
      max_clients?: number;
      max_users?: number;
      name: string;
      price: number;
      slug: string;
    };
    "models.PlanResponse": {
      active?: boolean;
      created_at?: string;
      currency?: string;
      description?: string;
      features?: string;
      id?: number;
      invoice_period?: string;
      max_clients?: number;
      max_users?: number;
      name?: string;
      price?: number;
      slug?: string;
    };
    "models.PlanUpdateRequest": {
      active?: boolean;
      currency?: string;
      description?: string;
      features?: string;
      invoice_period?: string;
      max_clients?: number;
      max_users?: number;
      name?: string;
      price?: number;
    };
    "models.TenantResponse": {
      created_at?: string;
      id?: number;
      name?: string;
      slug?: string;
    };
    "models.UpdateClientRequest": {
      /** @example 2025-01-01 */
      admission_date?: string;
      /** @example johnny.d@example.com */
      alternative_email?: string;
      /** @example Johnny */
      alternative_first_name?: string;
      /** @example D */
      alternative_last_name?: string;
      /** @example +0987654321 */
      alternative_phone?: string;
      /** @example New York */
      city?: string;
      /** @example jane.smith@example.com */
      contact_email?: string;
      /** @example Jane */
      contact_first_name?: string;
      /** @example Smith */
      contact_last_name?: string;
      /** @example +1234567890 */
      contact_phone?: string;
      /** @example 1990-01-15 */
      date_of_birth?: string;
      /** @example john.doe@example.com */
      email?: string;
      /** @example John */
      first_name?: string;
      /** @example male */
      gender?: string;
      /** @example false */
      invoiced_individually?: boolean;
      /** @example Doe */
      last_name?: string;
      /** @example Additional notes about the client */
      notes?: string;
      /** @example +1234567890 */
      phone?: string;
      /** @example English */
      primary_language?: string;
      /** @example PROV123456 */
      provider_approval_code?: string;
      /** @example Doctor Smith */
      referral_source?: string;
      /** @example active */
      status?: string;
      /** @example 123 Main Street */
      street_address?: string;
      /** @example Cognitive Behavioral Therapy */
      therapy_title?: string;
      /** @example 150 */
      unit_price?: number;
      /** @example 12345 */
      zip?: string;
    };
    "models.UserCreateRequest": {
      /** @description Terms and conditions acceptance */
      accept_terms?: boolean;
      /** @description Required unless user-signup token is present */
      company_name?: string;
      email: string;
      first_name: string;
      last_name: string;
      /** @description Newsletter subscription */
      newsletter_opt_in?: boolean;
      password: string;
      role?: string;
      username: string;
    };
    "models.UserResponse": {
      active?: boolean;
      created_at?: string;
      email?: string;
      email_verified?: boolean;
      email_verified_at?: string;
      first_name?: string;
      id?: number;
      last_name?: string;
      role?: string;
      tenant?: components["schemas"]["models.TenantResponse"];
      tenant_id?: number;
      username?: string;
    };
    "models.UserSettingsResponse": {
      id?: number;
      language?: string;
      settings?: string;
      theme?: string;
      timezone?: string;
      updated_at?: string;
      user_id?: number;
    };
    "models.UserSettingsUpdateRequest": {
      language?: string;
      settings?: string;
      theme?: string;
      timezone?: string;
    };
    "utils.PasswordRequirements": {
      capital?: boolean;
      minLength?: number;
      numbers?: boolean;
      special?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
