/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/pdf/create": {
    /**
     * Generate PDF from template
     * @description Generate a PDF document based on a specified template and data
     */
    post: {
      /** @description PDF generation request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_ae-base-server_modules_pdf_handlers.PDFGenerateRequest"];
        };
      };
      responses: {
        /** @description PDF generated successfully */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_pdf_handlers.PDFGenerateResponse"];
          };
        };
        /** @description Invalid request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_pdf_handlers.ErrorResponse"];
          };
        };
        /** @description Failed to generate PDF */
        500: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_pdf_handlers.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/forgot-password": {
    /**
     * Request password reset
     * @description Send password reset email to user
     */
    post: {
      /** @description Password reset request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.ForgotPasswordRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/login": {
    /**
     * User login
     * @description Authenticate user with username/email and password
     */
    post: {
      /** @description Login credentials */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.LoginRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.LoginResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/logout": {
    /**
     * User logout
     * @description Logout user and invalidate token
     */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/refresh": {
    /**
     * Refresh access token
     * @description Refresh user access token
     */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.LoginResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/register": {
    /**
     * User registration
     * @description Register a new user account
     */
    post: {
      /** @description User registration data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.UserCreateRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.LoginResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Conflict */
        409: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/reset-password": {
    /**
     * Reset password
     * @description Reset user password with reset token
     */
    post: {
      /** @description Password reset data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.ResetPasswordRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/auth/verify-email": {
    /**
     * Verify email address
     * @description Verify user email address with verification token
     */
    get: {
      parameters: {
        query: {
          /** @description Verification token */
          token: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/calendar": {
    /**
     * Get calendars with complete metadata
     * @description Retrieve all calendars for the authenticated user with 2-level deep preloading including entries with their series and series with their entries
     */
    get: {
      responses: {
        /** @description Array of calendars with preloaded entries, series, and external calendars */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CalendarResponse"][];
          };
        };
        /** @description Unauthorized - invalid or missing JWT token */
        401: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal server error during calendar retrieval */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Create a new calendar
     * @description Create a new calendar for the authenticated user
     */
    post: {
      /** @description Calendar data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.CreateCalendarRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["entities.CalendarResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/calendar-entries": {
    /**
     * Get all calendar entries
     * @description Retrieve all calendar entries for the authenticated user
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Create a new calendar entry
     * @description Create a new calendar entry
     */
    post: {
      /** @description Calendar entry data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.CreateCalendarEntryRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["entities.CalendarEntryResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/calendar-entries/{id}": {
    /**
     * Get calendar entry by ID
     * @description Retrieve a calendar entry by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Calendar Entry ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CalendarEntryResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Update calendar entry
     * @description Update an existing calendar entry
     */
    put: {
      parameters: {
        path: {
          /** @description Calendar Entry ID */
          id: number;
        };
      };
      /** @description Updated calendar entry data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.UpdateCalendarEntryRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CalendarEntryResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Delete calendar entry
     * @description Delete a calendar entry by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Calendar Entry ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/calendar-series": {
    /**
     * Get all calendar series
     * @description Retrieve all calendar series for the authenticated user
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Create a new calendar series
     * @description Create a new calendar series for recurring events
     */
    post: {
      /** @description Calendar series data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.CreateCalendarSeriesRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["entities.CalendarSeriesResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/calendar-series/{id}": {
    /**
     * Get calendar series by ID
     * @description Retrieve a calendar series by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Calendar Series ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CalendarSeriesResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Update calendar series
     * @description Update an existing calendar series
     */
    put: {
      parameters: {
        path: {
          /** @description Calendar Series ID */
          id: number;
        };
      };
      /** @description Updated calendar series data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.UpdateCalendarSeriesRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CalendarSeriesResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Delete calendar series
     * @description Delete a calendar series by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Calendar Series ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/calendar/free-slots": {
    /**
     * Get free time slots
     * @description Find available time slots based on duration, interval, and maximum number
     */
    get: {
      parameters: {
        query: {
          /** @description Duration in minutes */
          duration: number;
          /** @description Interval between slots in minutes */
          interval: number;
          /** @description Maximum number of slots to return */
          number_max: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.FreeSlot"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/calendar/import-holidays": {
    /**
     * Import holidays
     * @description Import holidays for a specific country and year
     */
    post: {
      /** @description Import holidays request */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.ImportHolidaysRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/calendar/week": {
    /**
     * Get calendar week view
     * @description Retrieve calendar entries for a specific week
     */
    get: {
      parameters: {
        query: {
          /** @description Date in YYYY-MM-DD format */
          date: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CalendarEntryResponse"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/calendar/year": {
    /**
     * Get calendar year view
     * @description Retrieve calendar entries for a specific year
     */
    get: {
      parameters: {
        query: {
          /** @description Year */
          year: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CalendarEntryResponse"][];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/calendar/{id}": {
    /**
     * Get calendar by ID
     * @description Retrieve a calendar by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Calendar ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CalendarResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Update calendar
     * @description Update an existing calendar
     */
    put: {
      parameters: {
        path: {
          /** @description Calendar ID */
          id: number;
        };
      };
      /** @description Updated calendar data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.UpdateCalendarRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CalendarResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Delete calendar
     * @description Delete a calendar by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Calendar ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/clients": {
    /**
     * Get all clients
     * @description Retrieve all clients with optional pagination
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Number of clients per page (respects DEFAULT_PAGE_LIMIT and MAX_PAGE_LIMIT env vars) */
          limit?: number;
        };
      };
      responses: {
        /** @description Clients retrieved successfully */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    /**
     * Create a new client
     * @description Create a new client with the provided information
     */
    post: {
      /** @description Client information */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.CreateClientRequest"];
        };
      };
      responses: {
        /** @description Created client */
        201: {
          content: {
            "application/json": components["schemas"]["entities.ClientResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/clients/search": {
    /**
     * Search clients
     * @description Search clients by first name or last name
     */
    get: {
      parameters: {
        query: {
          /** @description Search query */
          q: string;
          /** @description Page number */
          page?: number;
          /** @description Number of clients per page (respects DEFAULT_PAGE_LIMIT and MAX_PAGE_LIMIT env vars) */
          limit?: number;
        };
      };
      responses: {
        /** @description Search results */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/clients/{id}": {
    /**
     * Get a client by ID
     * @description Retrieve a specific client by their ID
     */
    get: {
      parameters: {
        path: {
          /** @description Client ID */
          id: number;
        };
      };
      responses: {
        /** @description Client found */
        200: {
          content: {
            "application/json": components["schemas"]["entities.ClientResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Client not found */
        404: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    /**
     * Update a client
     * @description Update a client's information
     */
    put: {
      parameters: {
        path: {
          /** @description Client ID */
          id: number;
        };
      };
      /** @description Updated client information */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.UpdateClientRequest"];
        };
      };
      responses: {
        /** @description Updated client */
        200: {
          content: {
            "application/json": components["schemas"]["entities.ClientResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Client not found */
        404: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    /**
     * Delete a client
     * @description Soft delete a client by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Client ID */
          id: number;
        };
      };
      responses: {
        /** @description Client deleted successfully */
        200: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Client not found */
        404: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/contact/form": {
    /**
     * Submit contact form
     * @description Submit a contact form and optionally subscribe to newsletter
     */
    post: {
      /** @description Contact form data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ContactFormRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ContactFormResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contact/newsletter": {
    /**
     * Get newsletter subscriptions
     * @description Get all newsletter subscriptions for admin users
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.Newsletter"][];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/contact/newsletter/unsubscribe": {
    /**
     * Unsubscribe from newsletter
     * @description Unsubscribe an email from the newsletter
     */
    delete: {
      parameters: {
        query: {
          /** @description Email to unsubscribe */
          email: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/cost-providers": {
    /**
     * Get all cost providers
     * @description Retrieve all cost providers with optional pagination
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Number of cost providers per page (respects DEFAULT_PAGE_LIMIT and MAX_PAGE_LIMIT env vars) */
          limit?: number;
        };
      };
      responses: {
        /** @description Cost providers retrieved successfully */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    /**
     * Create a new cost provider
     * @description Create a new cost provider with the provided information
     */
    post: {
      /** @description Cost provider information */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.CreateCostProviderRequest"];
        };
      };
      responses: {
        /** @description Created cost provider */
        201: {
          content: {
            "application/json": components["schemas"]["entities.CostProviderResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/cost-providers/search": {
    /**
     * Search cost providers
     * @description Search cost providers by organization name or contact name
     */
    get: {
      parameters: {
        query: {
          /** @description Search query */
          q: string;
          /** @description Page number */
          page?: number;
          /** @description Number of cost providers per page (respects DEFAULT_PAGE_LIMIT and MAX_PAGE_LIMIT env vars) */
          limit?: number;
        };
      };
      responses: {
        /** @description Search results */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/cost-providers/{id}": {
    /**
     * Get a cost provider by ID
     * @description Retrieve a specific cost provider by their ID
     */
    get: {
      parameters: {
        path: {
          /** @description Cost Provider ID */
          id: number;
        };
      };
      responses: {
        /** @description Cost provider found */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CostProviderResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Cost provider not found */
        404: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    /**
     * Update a cost provider
     * @description Update a cost provider's information
     */
    put: {
      parameters: {
        path: {
          /** @description Cost Provider ID */
          id: number;
        };
      };
      /** @description Updated cost provider information */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.UpdateCostProviderRequest"];
        };
      };
      responses: {
        /** @description Updated cost provider */
        200: {
          content: {
            "application/json": components["schemas"]["entities.CostProviderResponse"];
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Cost provider not found */
        404: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
    /**
     * Delete a cost provider
     * @description Soft delete a cost provider by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Cost Provider ID */
          id: number;
        };
      };
      responses: {
        /** @description Cost provider deleted successfully */
        200: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Cost provider not found */
        404: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
        /** @description Internal server error */
        500: {
          content: {
            "application/json": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/customers": {
    /**
     * Get all customers
     * @description Get a paginated list of all customers
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.ListResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create a new customer
     * @description Create a new customer
     */
    post: {
      /** @description Customer data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.CustomerRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.CustomerResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/customers/{id}": {
    /**
     * Get customer by ID
     * @description Get a specific customer by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Customer ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.CustomerResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update a customer
     * @description Update an existing customer by ID
     */
    put: {
      parameters: {
        path: {
          /** @description Customer ID */
          id: number;
        };
      };
      /** @description Updated customer data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.CustomerRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.CustomerResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete a customer
     * @description Soft delete a customer by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description Customer ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails": {
    /**
     * Get all emails
     * @description Get a paginated list of all emails
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
          /** @description Filter by email status */
          status?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_internal_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_internal_models.ListResponse"];
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_internal_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails/send": {
    /**
     * Send an email
     * @description Create and queue an email for sending
     */
    post: {
      /** @description Email send data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["github_com_ae-base-server_internal_models.EmailSendRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_internal_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_internal_models.EmailResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_internal_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails/stats": {
    /**
     * Get email statistics
     * @description Get email statistics including counts by status
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_internal_models.APIResponse"] & {
              data?: Record<string, never>;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_internal_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/emails/{id}": {
    /**
     * Get email by ID
     * @description Get a specific email by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Email ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_internal_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_internal_models.EmailResponse"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_internal_models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_internal_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/external-calendars": {
    /**
     * Get all external calendars
     * @description Retrieve all external calendars for the authenticated user
     */
    get: {
      parameters: {
        query?: {
          /** @description Page number */
          page?: number;
          /** @description Items per page */
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Create a new external calendar
     * @description Create a new external calendar
     */
    post: {
      /** @description External calendar data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.CreateExternalCalendarRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["entities.ExternalCalendarResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/external-calendars/{id}": {
    /**
     * Get external calendar by ID
     * @description Retrieve an external calendar by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description External Calendar ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.ExternalCalendarResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Update external calendar
     * @description Update an existing external calendar
     */
    put: {
      parameters: {
        path: {
          /** @description External Calendar ID */
          id: number;
        };
      };
      /** @description Updated external calendar data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["entities.UpdateExternalCalendarRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["entities.ExternalCalendarResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    /**
     * Delete external calendar
     * @description Delete an external calendar by ID
     */
    delete: {
      parameters: {
        path: {
          /** @description External Calendar ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": {
              [key: string]: unknown;
            };
          };
        };
      };
    };
  };
  "/health": {
    /**
     * Health check
     * @description Check the health status of the API and database
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.HealthResponse"];
          };
        };
        /** @description Service Unavailable */
        503: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/ping": {
    /**
     * Ping check
     * @description Simple ping endpoint
     */
    get: {
      responses: {
        /** @description pong */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
    };
  };
  "/plans": {
    /**
     * Get all plans
     * @description Get a list of all available subscription plans
     */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.Plan"][];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Create a new plan
     * @description Create a new subscription plan (admin only)
     */
    post: {
      /** @description Plan data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.PlanRequest"];
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.Plan"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/plans/{id}": {
    /**
     * Get plan by ID
     * @description Get a specific subscription plan by its ID
     */
    get: {
      parameters: {
        path: {
          /** @description Plan ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.Plan"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Update a plan
     * @description Update an existing subscription plan (admin only)
     */
    put: {
      parameters: {
        path: {
          /** @description Plan ID */
          id: number;
        };
      };
      /** @description Updated plan data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["models.PlanRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"] & {
              data?: components["schemas"]["github_com_ae-base-server_modules_base_models.Plan"];
            };
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
    /**
     * Delete a plan
     * @description Delete a subscription plan (admin only)
     */
    delete: {
      parameters: {
        path: {
          /** @description Plan ID */
          id: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.APIResponse"];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
        /** @description Not Found */
        404: {
          content: {
            "application/json": components["schemas"]["github_com_ae-base-server_modules_base_models.ErrorResponse"];
          };
        };
      };
    };
  };
  "/static": {
    /**
     * List available static JSON files
     * @description Get a list of all JSON files available in the statics/json directory
     */
    get: {
      responses: {
        /** @description List of available JSON files */
        200: {
          content: {
            "*/*": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Failed to read directory */
        500: {
          content: {
            "*/*": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
  "/static/{filename}": {
    /**
     * Serve static JSON files (JSON only, security restricted)
     * @description Securely serve JSON data files from statics/json directory only. Prevents access to other directories or file types.
     */
    get: {
      parameters: {
        path: {
          /**
           * @description JSON filename (without .json extension)
           * @example "bundeslaender"
           */
          filename: string;
        };
      };
      responses: {
        /** @description JSON file content */
        200: {
          content: {
            "*/*": {
              [key: string]: unknown;
            };
          };
        };
        /** @description Invalid file name */
        400: {
          content: {
            "*/*": {
              [key: string]: string;
            };
          };
        };
        /** @description File not found */
        404: {
          content: {
            "*/*": {
              [key: string]: string;
            };
          };
        };
        /** @description Failed to read file */
        500: {
          content: {
            "*/*": {
              [key: string]: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "entities.CalendarEntryResponse": {
      calendar_id?: number;
      created_at?: string;
      date_from?: string;
      date_to?: string;
      description?: string;
      id?: number;
      is_all_day?: boolean;
      is_exception?: boolean;
      location?: string;
      participants?: number[];
      series_id?: number;
      tenant_id?: number;
      time_from?: string;
      time_to?: string;
      timezone?: string;
      title?: string;
      type?: string;
      updated_at?: string;
      user_id?: number;
    };
    "entities.CalendarResponse": {
      calendar_entries?: components["schemas"]["entities.CalendarEntryResponse"][];
      calendar_series?: components["schemas"]["entities.CalendarSeriesResponse"][];
      calendar_uuid?: string;
      color?: string;
      created_at?: string;
      external_calendars?: components["schemas"]["entities.ExternalCalendarResponse"][];
      id?: number;
      tenant_id?: number;
      timezone?: string;
      title?: string;
      updated_at?: string;
      user_id?: number;
      weekly_availability?: number[];
    };
    "entities.CalendarSeriesResponse": {
      calendar_id?: number;
      created_at?: string;
      description?: string;
      entry_uuid?: string;
      external_calendar_uuid?: string;
      external_uid?: string;
      id?: number;
      interval?: number;
      location?: string;
      participants?: number[];
      sequence?: number;
      tenant_id?: number;
      time_end?: string;
      time_start?: string;
      title?: string;
      updated_at?: string;
      user_id?: number;
      weekday?: number;
    };
    "entities.ClientResponse": {
      admission_date?: string;
      alternative_email?: string;
      alternative_first_name?: string;
      alternative_last_name?: string;
      alternative_phone?: string;
      city?: string;
      contact_email?: string;
      contact_first_name?: string;
      contact_last_name?: string;
      contact_phone?: string;
      cost_provider?: components["schemas"]["entities.CostProviderResponse"];
      cost_provider_id?: number;
      created_at?: string;
      date_of_birth?: string;
      email?: string;
      first_name?: string;
      gender?: string;
      id?: number;
      invoiced_individually?: boolean;
      last_name?: string;
      notes?: string;
      phone?: string;
      primary_language?: string;
      provider_approval_code?: string;
      provider_approval_date?: string;
      referral_source?: string;
      status?: string;
      street_address?: string;
      tenant_id?: number;
      therapy_title?: string;
      unit_price?: number;
      updated_at?: string;
      zip?: string;
    };
    "entities.CostProviderResponse": {
      city?: string;
      contact_name?: string;
      created_at?: string;
      department?: string;
      id?: number;
      organization?: string;
      street_address?: string;
      tenant_id?: number;
      updated_at?: string;
      zip?: string;
    };
    "entities.CreateCalendarEntryRequest": Record<string, never>;
    "entities.CreateCalendarRequest": Record<string, never>;
    "entities.CreateCalendarSeriesRequest": Record<string, never>;
    "entities.CreateClientRequest": Record<string, never>;
    "entities.CreateCostProviderRequest": {
      /** @example New York */
      city?: string;
      /** @example Jane Smith */
      contact_name?: string;
      /** @example Mental Health Division */
      department?: string;
      /** @example Health Insurance Corp */
      organization: string;
      /** @example 456 Insurance Blvd */
      street_address?: string;
      /** @example 12345 */
      zip?: string;
    };
    "entities.CreateExternalCalendarRequest": Record<string, never>;
    "entities.ExternalCalendarResponse": {
      calendar_id?: number;
      calendar_uuid?: string;
      color?: string;
      created_at?: string;
      id?: number;
      settings?: number[];
      sync_last_run?: string;
      tenant_id?: number;
      title?: string;
      updated_at?: string;
      url?: string;
      user_id?: number;
    };
    "entities.FreeSlot": {
      /** @example 60 */
      duration?: number;
      /** @example 2025-01-15T10:00:00Z */
      end_time?: string;
      /** @example 2025-01-15T09:00:00Z */
      start_time?: string;
    };
    "entities.ImportHolidaysRequest": {
      /** @example US */
      country: string;
      /** @example 2025 */
      year: number;
    };
    "entities.NullableDate": {
      "time.Time"?: string;
    };
    "entities.UpdateCalendarEntryRequest": Record<string, never>;
    "entities.UpdateCalendarRequest": Record<string, never>;
    "entities.UpdateCalendarSeriesRequest": Record<string, never>;
    "entities.UpdateClientRequest": Record<string, never>;
    "entities.UpdateCostProviderRequest": {
      /** @example New York */
      city?: string;
      /** @example Jane Smith */
      contact_name?: string;
      /** @example Mental Health Division */
      department?: string;
      /** @example Health Insurance Corp */
      organization?: string;
      /** @example 456 Insurance Blvd */
      street_address?: string;
      /** @example 12345 */
      zip?: string;
    };
    "entities.UpdateExternalCalendarRequest": Record<string, never>;
    "github_com_ae-base-server_internal_models.APIResponse": {
      data?: unknown;
      error?: string;
      message?: string;
      success?: boolean;
    };
    "github_com_ae-base-server_internal_models.EmailResponse": {
      created_at?: string;
      delivered_at?: string;
      error_message?: string;
      from?: string;
      id?: number;
      sent_at?: string;
      status?: string;
      subject?: string;
      to?: string;
    };
    "github_com_ae-base-server_internal_models.EmailSendRequest": {
      body: string;
      from: string;
      html_body?: string;
      subject: string;
      to: string;
    };
    "github_com_ae-base-server_internal_models.ErrorResponse": {
      code?: number;
      details?: string;
      error?: string;
    };
    "github_com_ae-base-server_internal_models.ListResponse": {
      data?: unknown;
      pagination?: components["schemas"]["github_com_ae-base-server_internal_models.PaginationResponse"];
    };
    "github_com_ae-base-server_internal_models.PaginationResponse": {
      limit?: number;
      page?: number;
      total?: number;
      total_pages?: number;
    };
    "github_com_ae-base-server_modules_base_models.APIResponse": {
      data?: unknown;
      error?: string;
      message?: string;
      success?: boolean;
    };
    "github_com_ae-base-server_modules_base_models.ContactFormRequest": {
      /** @example john@example.com */
      email: string;
      /** @example I would like to know more about your services. */
      message: string;
      /** @example John Doe */
      name: string;
      /** @example Inquiry about services */
      subject: string;
    };
    "github_com_ae-base-server_modules_base_models.ContactFormResponse": {
      /** @example 1 */
      id?: number;
      /** @example Thank you for your message! We will get back to you soon. */
      message?: string;
    };
    "github_com_ae-base-server_modules_base_models.CustomerResponse": {
      /** @example Acme Corp */
      company_name?: string;
      /** @example 2023-01-01T00:00:00Z */
      created_at?: string;
      /** @example john@example.com */
      email?: string;
      /** @example 1 */
      id?: number;
      /** @example John Doe */
      name?: string;
      /** @example +1-555-123-4567 */
      phone?: string;
      /** @example 2023-01-01T00:00:00Z */
      updated_at?: string;
    };
    "github_com_ae-base-server_modules_base_models.ErrorResponse": {
      code?: number;
      details?: string;
      error?: string;
    };
    "github_com_ae-base-server_modules_base_models.HealthResponse": {
      database?: string;
      environment?: {
        [key: string]: unknown;
      };
      status?: string;
      timestamp?: string;
      version?: string;
    };
    "github_com_ae-base-server_modules_base_models.ListResponse": {
      data?: unknown;
      pagination?: components["schemas"]["github_com_ae-base-server_modules_base_models.PaginationResponse"];
    };
    "github_com_ae-base-server_modules_base_models.LoginRequest": {
      /** @example user@example.com */
      email: string;
      /** @example password123 */
      password: string;
    };
    "github_com_ae-base-server_modules_base_models.LoginResponse": {
      /** @example refresh-token-123 */
      refresh_token?: string;
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      token?: string;
      user?: components["schemas"]["github_com_ae-base-server_modules_base_models.UserResponse"];
    };
    "github_com_ae-base-server_modules_base_models.Newsletter": {
      /** @example 2023-01-01T00:00:00Z */
      created_at?: string;
      /** @example user@example.com */
      email?: string;
      /** @example 1 */
      id?: number;
      /** @example true */
      is_active?: boolean;
    };
    "github_com_ae-base-server_modules_base_models.PaginationResponse": {
      /** @example 10 */
      limit?: number;
      /** @example 1 */
      page?: number;
      /** @example 100 */
      total?: number;
      /** @example 10 */
      total_pages?: number;
    };
    "github_com_ae-base-server_modules_base_models.Plan": {
      /** @example 2023-01-01T00:00:00Z */
      created_at?: string;
      /** @example USD */
      currency?: string;
      /** @example Basic subscription plan */
      description?: string;
      /** @example 1 */
      id?: number;
      /** @example true */
      is_active?: boolean;
      /** @example Basic Plan */
      name?: string;
      /** @example 29.99 */
      price?: number;
      /** @example 2023-01-01T00:00:00Z */
      updated_at?: string;
    };
    "github_com_ae-base-server_modules_base_models.TenantResponse": {
      /** @example Acme Corp */
      display_name?: string;
      /** @example 1 */
      id?: number;
      /** @example true */
      is_active?: boolean;
      /** @example acme */
      name?: string;
    };
    "github_com_ae-base-server_modules_base_models.UserCreateRequest": {
      /** @example Acme Corp */
      company_name?: string;
      /** @example user@example.com */
      email: string;
      /** @example John */
      first_name: string;
      /** @example Doe */
      last_name: string;
      /** @example password123 */
      password: string;
      /** @example acme */
      tenant_name: string;
    };
    "github_com_ae-base-server_modules_base_models.UserResponse": {
      /** @example Acme Corp */
      company_name?: string;
      /** @example user@example.com */
      email?: string;
      /** @example John */
      first_name?: string;
      /** @example 1 */
      id?: number;
      /** @example true */
      is_active?: boolean;
      /** @example Doe */
      last_name?: string;
      tenant?: components["schemas"]["github_com_ae-base-server_modules_base_models.TenantResponse"];
    };
    "github_com_ae-base-server_modules_pdf_handlers.ErrorResponse": {
      /** @example Additional error details */
      details?: string;
      /** @example Template name is required */
      error?: string;
    };
    "github_com_ae-base-server_modules_pdf_handlers.PDFGenerateRequest": {
      data?: {
        [key: string]: unknown;
      };
      /** @example generated-report */
      fileName?: string;
      /** @example report.html */
      templateName?: string;
    };
    "github_com_ae-base-server_modules_pdf_handlers.PDFGenerateResponse": {
      /** @example generated-report.pdf */
      filename?: string;
      /** @example PDF generated successfully */
      message?: string;
      /** @example true */
      success?: boolean;
    };
    "models.ClientResponse": {
      admission_date?: string;
      alternative_email?: string;
      alternative_first_name?: string;
      alternative_last_name?: string;
      alternative_phone?: string;
      city?: string;
      contact_email?: string;
      contact_first_name?: string;
      contact_last_name?: string;
      contact_phone?: string;
      cost_provider?: components["schemas"]["models.CostProviderResponse"];
      cost_provider_id?: number;
      created_at?: string;
      date_of_birth?: string;
      email?: string;
      first_name?: string;
      gender?: string;
      id?: number;
      invoiced_individually?: boolean;
      last_name?: string;
      notes?: string;
      phone?: string;
      primary_language?: string;
      provider_approval_code?: string;
      provider_approval_date?: string;
      referral_source?: string;
      status?: string;
      street_address?: string;
      tenant_id?: number;
      therapy_title?: string;
      unit_price?: number;
      updated_at?: string;
      zip?: string;
    };
    "models.CostProviderResponse": {
      city?: string;
      contact_name?: string;
      created_at?: string;
      department?: string;
      id?: number;
      organization?: string;
      street_address?: string;
      tenant_id?: number;
      updated_at?: string;
      zip?: string;
    };
    "models.CreateClientRequest": {
      /** @example 2025-01-01 */
      admission_date?: string;
      /** @example johnny.d@example.com */
      alternative_email?: string;
      /** @example Johnny */
      alternative_first_name?: string;
      /** @example D */
      alternative_last_name?: string;
      /** @example +0987654321 */
      alternative_phone?: string;
      /** @example New York */
      city?: string;
      /** @example jane.smith@example.com */
      contact_email?: string;
      /** @example Jane */
      contact_first_name?: string;
      /** @example Smith */
      contact_last_name?: string;
      /** @example +1234567890 */
      contact_phone?: string;
      /** @example 1 */
      cost_provider_id?: number;
      /** @example 1990-01-15 */
      date_of_birth?: string;
      /** @example john.doe@example.com */
      email?: string;
      /** @example John */
      first_name: string;
      /** @example male */
      gender?: string;
      /** @example false */
      invoiced_individually?: boolean;
      /** @example Doe */
      last_name: string;
      /** @example Additional notes about the client */
      notes?: string;
      /** @example +1234567890 */
      phone?: string;
      /** @example English */
      primary_language?: string;
      /** @example PROV123456 */
      provider_approval_code?: string;
      /** @example 2025-01-15 */
      provider_approval_date?: string;
      /** @example Doctor Smith */
      referral_source?: string;
      /** @example waiting */
      status?: string;
      /** @example 123 Main Street */
      street_address?: string;
      /** @example Cognitive Behavioral Therapy */
      therapy_title?: string;
      /** @example 150 */
      unit_price?: number;
      /** @example 12345 */
      zip?: string;
    };
    "models.CreateCostProviderRequest": {
      /** @example New York */
      city?: string;
      /** @example Jane Smith */
      contact_name?: string;
      /** @example Mental Health Division */
      department?: string;
      /** @example Health Insurance Corp */
      organization: string;
      /** @example 456 Insurance Blvd */
      street_address?: string;
      /** @example 12345 */
      zip?: string;
    };
    "models.CustomerRequest": {
      /** @example Acme Corp */
      company_name?: string;
      /** @example john@example.com */
      email: string;
      /** @example John Doe */
      name: string;
      /** @example +1-555-123-4567 */
      phone?: string;
    };
    "models.ForgotPasswordRequest": {
      /** @example user@example.com */
      email: string;
    };
    "models.PlanRequest": {
      /** @example USD */
      currency: string;
      /** @example Basic subscription plan */
      description?: string;
      /** @example Basic Plan */
      name: string;
      /** @example 29.99 */
      price: number;
    };
    "models.ResetPasswordRequest": {
      /** @example newpassword123 */
      password: string;
      /** @example reset-token-123 */
      token: string;
    };
    "models.UpdateClientRequest": {
      /** @example 2025-01-01 */
      admission_date?: string;
      /** @example johnny.d@example.com */
      alternative_email?: string;
      /** @example Johnny */
      alternative_first_name?: string;
      /** @example D */
      alternative_last_name?: string;
      /** @example +0987654321 */
      alternative_phone?: string;
      /** @example New York */
      city?: string;
      /** @example jane.smith@example.com */
      contact_email?: string;
      /** @example Jane */
      contact_first_name?: string;
      /** @example Smith */
      contact_last_name?: string;
      /** @example +1234567890 */
      contact_phone?: string;
      /** @example 1 */
      cost_provider_id?: number;
      /** @example 1990-01-15 */
      date_of_birth?: string;
      /** @example john.doe@example.com */
      email?: string;
      /** @example John */
      first_name?: string;
      /** @example male */
      gender?: string;
      /** @example false */
      invoiced_individually?: boolean;
      /** @example Doe */
      last_name?: string;
      /** @example Additional notes about the client */
      notes?: string;
      /** @example +1234567890 */
      phone?: string;
      /** @example English */
      primary_language?: string;
      /** @example PROV123456 */
      provider_approval_code?: string;
      /** @example 2025-01-15 */
      provider_approval_date?: string;
      /** @example Doctor Smith */
      referral_source?: string;
      /** @example active */
      status?: string;
      /** @example 123 Main Street */
      street_address?: string;
      /** @example Cognitive Behavioral Therapy */
      therapy_title?: string;
      /** @example 150 */
      unit_price?: number;
      /** @example 12345 */
      zip?: string;
    };
    "models.UpdateCostProviderRequest": {
      /** @example New York */
      city?: string;
      /** @example Jane Smith */
      contact_name?: string;
      /** @example Mental Health Division */
      department?: string;
      /** @example Health Insurance Corp */
      organization?: string;
      /** @example 456 Insurance Blvd */
      street_address?: string;
      /** @example 12345 */
      zip?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
